Feat/add odom publisher
ros-drivers/mocap_optitrack pull request #52
Opened 2021-02-16 14:49 UTC by jadhm

2021-02-16 14:57 UTC, jadhm commented
It's handy to have published Odometry messages as well as Poses. 
@tonybaltovski  Would you like to take a look at this pull request ?

2021-02-23 10:48 UTC, jadhm commented
ping @tonybaltovski @yamokosk @abencz

2021-02-23 23:13 UTC, tonybaltovski requested changes
Just some minor nits.

2021-02-23 23:13 UTC, tonybaltovski commented on src/rigid_body_publisher.cpp
> +    {
Fix spacing please.

2021-02-23 23:13 UTC, tonybaltovski commented on src/rigid_body_publisher.cpp
> +    else if (coordinatesVersion < Version("2.0") && coordinatesVersion >= Version("1.7")) {
Brace should be on a new line.

2021-02-24 12:39 UTC, tonybaltovski approved these changes

2021-02-24 12:40 UTC, tonybaltovski approved these changes

2021-02-24 12:40 UTC, merged